version: "3.9"

services:
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok_server
    restart: always
    command:
      - start
      - --all
      - --config=/etc/ngrok/ngrok.yml
    volumes:
      - ./ngrok_config:/etc/ngrok
    ports:
      - "4040:4040"
    networks:
      - app_network

networks:
  app_network:
    name: project_app_network
    external: true
